-- MySQL Script generated by MySQL Workbench
-- Wed Dec 26 13:26:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Kredit` FLOAT NOT NULL DEFAULT 0,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(45) NOT NULL,
  `Popis` LONGTEXT NOT NULL,
  `Rok_vydani` DATETIME NULL,
  `URL` VARCHAR(45) NOT NULL,
  `Cena` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pujceno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pujceno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Videa_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `Datum_vypujceni` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Datum_EXPIRACE` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pujceno_Videa1_idx` (`Videa_id` ASC) VISIBLE,
  INDEX `fk_Pujceno_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pujceno_Videa1`
    FOREIGN KEY (`Videa_id`)
    REFERENCES `mydb`.`Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pujceno_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Texty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Texty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Premium` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Aktivni_od` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Aktivni_do` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Premium_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Premium_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nazev` VARCHAR(45) NOT NULL,
  `Popis` LONGTEXT NULL,
  `fotka` VARCHAR(200) NOT NULL,
  `Video_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Video_id`),
  INDEX `fk_Foto_Video1_idx` (`Video_id` ASC) VISIBLE,
  CONSTRAINT `fk_Foto_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `mydb`.`Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trailer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `popis` LONGTEXT NULL,
  `URL` VARCHAR(200) NULL,
  `Video_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Video_id`),
  INDEX `fk_trailer_Video1_idx` (`Video_id` ASC) VISIBLE,
  CONSTRAINT `fk_trailer_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `mydb`.`Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shlednuto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shlednuto` (
  `user_id` INT NOT NULL,
  `Video_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_has_Video_Video1_idx` (`Video_id` ASC) VISIBLE,
  INDEX `fk_user_has_Video_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_Video_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Video_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `mydb`.`Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;